### PR TITLE
Refactored __export_to_bam function and separated it into its own file

### PR DESCRIPTION
**Pull request by berylliumquestion**
I started doing this because I was wondering about how I could add egg support so I thought I'd poke around the bam expoerter, but the function was hard for me to read and understand, so I broke it down until it made sense _to me_ and maybe it might be easier for other people too. It still exports the model primitives and the collision primitives as well as basic_geom. I'm not sure about every material, because I don't quite know how to test those... yet, but I know at least 1 or 2 of the conditions there works. So, let me know what you think.

### CODE REVIEW

**Comment by Epihaius** [comment]
Extending the export functionality is certainly a good idea, and I agree with splitting off the main code into a subpackage.
While there are some issues, your current refactoring does make things more readable, so I'm grateful that you want to do this!

A couple of problems I encountered when testing out your changes:
* `directory` in `__create_texture_filenames` should be `self.directory`;
* `__process_basic_geom` doesn't seem to be implemented yet, so it's currently not possible to export BasicGeom objects that are part of a Collision Group.

Then there are some methods I'd like to see changed, if you don't mind:
* rename `__check_model_geom_type(self, coll_solid, scale)` to `__create_collision_solid(self, scale)`, with the initialization of `coll_solid` to `None` in that method instead of in `__create_collision_node`;
* rename `__create_*_collision_geom` to `__create_*_collision_solid`;
* rename `__*_processing` to `__process_*s` (also more consistent with `__process_basic_geom`);
* rename `__check_box_normals(self, dimensions_sizes, center)` to `__create_inverted_box_planes(self, dimensions, center)` and instead of `coll_solid`, make it return `True` (when CollisionPlanes were created) or `False`, in which case the CollisionBox should be created in `__create_box_collision_solid`.

Also, if you don't mind, in terms of code formatting - specifically blank space - I'd like to see:
* one blank line between class/method header and body;
* two blank lines between module-level classes/functions.

Sorry if this seems like nitpicking, but it would just make the formatting more consistent with the rest of my project. Thanks!

Regarding the .egg format, that's actually how I started my implementation of model export. The reason I gave up on it was that export to .bam was a lot easier, but also because the data in the .bam file is pretty much an exact copy of the internal Panda structures used to represent the model. There are things like multitexturing that I wouldn't even know how to put into an .egg file. The only reason I see to even use an .egg file is that it can easily be edited, but using this project of mine should make that unnecessary.
If you really want to add export to .egg functionality I won't stop you, but then I expect you to take full responsibility of its implementation, as I'm personally not really interested in it. And don't forget there's bam2egg... ;) .

What I would like to see is export to additional 3D file formats, so use of my project wouldn't be limited to Panda3D users. There's already support for .obj, but it hasn't been properly maintained. In particular, exporting groups isn't possible yet. If you could help with that, I would appreciate that tremendously, but if you don't feel like it, that's OK too.

In any case, I'd like to do some more thorough testing of your work in progress, but as I'm currently working on a side project, it might take a while before I can get to it.

**Comment by berylliumquestion** [comment]
Actually, I was thinking about doing this for the __export_to_obj function, but I wanted to see what you thought of what I did so far before I started that. As for adding support for groups, I'm not sure what that even is unfortunately, so I'm not sure if I can be much help there. Is that like when you parent an object to another?

**Comment by Epihaius** [comment]
In my project there are two ways to attach objects: "linking" and grouping. Under the hood, both of these are indeed implemented using the exact same Panda parenting system.
If you want to build a hierarchy of objects, you'll likely want to link child objects to parent objects.
If you want to treat multiple objects as a whole, a monolithic unit, then grouping them all together is an easy way to do that. But groups have an additional purpose: they affect how their member objects will be exported. The member type of the group determines how exactly this will happen. You already know about collision-type groups, but also the model-type group makes its members export in a very special way: they will become Geoms that are all added to the same GeomNode. (If you don't want this to happen, just leave the member type to its default, "Any".) For example if you want to create a sword, you first model the blade and the hilt separately, texture them and finally group them so you can further edit them together as just "the sword". When you load the exported .bam file in your own Panda application, you will also get just a single NodePath, making it easy to reparent, transform etc.

As for .obj export of grouped models, that was a nice surprise: it was actually very easy to add, so I already pushed a fix :) .

Thanks for your recent changes, that's starting to look quite good.

There are still a couple of instances where you forgot to prepend a variable with "`self.`":
* line 108: `child`
* line 111: `geom_node`
* line 167: `group_pivot`

Then there's a little mistake on line 286, which should read:

`        if not has_inverted_normals:`

or even more readable:

`        if not self.__create_inverted_box_planes(dimensions, center):`

(as in: "If creation of inverted box planes failed, create a regular box"), then you don't need the `has_inverted_normals` variable.

Lastly, I encountered a bug where not all members of a collision group were exported as collision solids, but as GeomNode children of the CollisionNode, which doesn't appear to be happening in my own code.
It's not trivial to reproduce, so I'll need to do more in-depth checking of what's going wrong, but I haven't got time for it right now.

**Comment by berylliumquestion** [comment]
Oh dear. That's a bit odd about the collision solids. So, when you say there are cases when not all members of a collision group were exported correctly is that when you have multiple primitives parented to one group and then turned into collision solids, but instead of all of them being exported as collision solids, sometimes they turn out as a plain model would? Even though I have nothing but time right now, I'm not sure what's even going on with that. Well, whenever you get to it I'll be here, at least for the next few months.

**Comment by Epihaius** [comment]
> So, when you say there are cases when not all members of a collision group were exported correctly is that when you have multiple primitives parented to one group and then turned into collision solids, but instead of all of them being exported as collision solids, sometimes they turn out as a plain model would?

That does seem to be the case. Although it might be related to the fact that the last model added to the group was not a primitive, but a BasicGeom (it's also the selected object when exporting, although that shouldn't matter). Not sure though.

Attached is a saved scene file that contains a hierarchy with a collision group. Whenever I export it using your fork, the result is like the .bam file that is also in the attached archive.
To verify, open the scene file, don't (de)select anything but immediately do an export; perhaps you can add some `print` calls to your export code at various points in the export process to check how the hierarchy attached to `self.root` is being built up.

[export_test.zip](https://github.com/Epihaius/panda3dstudio/files/3195339/export_test.zip)

**Comment by berylliumquestion** [comment]
I think that specific problem was due to the fact that I was reassigning self.collision_node in the __check_if_basic_geom method, even though neither of the process methods returned anything. I think I also found another bug involving planes and being exported in the wrong position, but I can't quite remember how I did it because I was trying to recreate what you were talking about.

-------

One thing to note is that depending on the order the objects are selected in results in a differing amount of collision solids. When basic_geom is the first member this is debug info I got when I exported a cube basic_geom, a sphere primitive, and a cylinder primitive:

child loop, self.collision_node: None
child loop, self.child: <src.core.helpers.group.Group object at 0x7f5f6feca128>
child loop, self.collision_node: CollisionNode group 0001 (0 solids) T:(pos -0.319807 1.11375 2.95661) (hidden)

child loop, self.child: <src.core.geom.model.Model object at 0x7f5f6fec3128>
how many times?
self.collision_node: CollisionNode group 0001 (0 solids) T:(pos -0.319807 1.11375 2.95661) (hidden)

should be three times
child loop, self.collision_node: CollisionNode group 0001 (12 solids) T:(pos -0.319807 1.11375 2.95661) (hidden)

child loop, self.child: <src.core.geom.model.Model object at 0x7f5f6fec3ac8>
how many times?
self.collision_node: CollisionNode group 0001 (12 solids) T:(pos -0.319807 1.11375 2.95661) (hidden)

should be three times
child loop, self.collision_node: CollisionNode group 0001 (13 solids) T:(pos -0.319807 1.11375 2.95661) (hidden)

child loop, self.child: <src.core.geom.model.Model object at 0x7f5f85f86b38>
how many times?
self.collision_node: CollisionNode group 0001 (13 solids) T:(pos -0.319807 1.11375 2.95661) (hidden)

should be three times

------

Here's the debug information I got when I selected one of the primitives first:

child loop, self.collision_node: None
child loop, self.child: <src.core.helpers.group.Group object at 0x7f45bc116080>
child loop, self.collision_node: CollisionNode group 0001 (0 solids) T:(pos -1.09291 1.08048 2.3484) (hidden)

child loop, self.child: <src.core.geom.model.Model object at 0x7f4594148390>
how many times?
self.collision_node: CollisionNode group 0001 (0 solids) T:(pos -1.09291 1.08048 2.3484) (hidden)

should be three times
child loop, self.collision_node: CollisionNode group 0001 (1 solids) T:(pos -1.09291 1.08048 2.3484) (hidden)

child loop, self.child: <src.core.geom.model.Model object at 0x7f459414d320>
how many times?
self.collision_node: CollisionNode group 0001 (1 solids) T:(pos -1.09291 1.08048 2.3484) (hidden)

should be three times
child loop, self.collision_node: CollisionNode group 0001 (2 solids) T:(pos -1.09291 1.08048 2.3484) (hidden)

child loop, self.child: <src.core.geom.model.Model object at 0x7f459413af60>
how many times?
self.collision_node: CollisionNode group 0001 (2 solids) T:(pos -1.09291 1.08048 2.3484) (hidden)

should be three times

------

Let me know if there's anything else I need to fix!

**Comment by Epihaius** [comment]
Thanks for looking into this! It does seem to work now.

When I have more time I'll do some additional testing myself.

**Comment by Epihaius** [comment]
Finally I had time to look into this further and everything seems to work fine, so I'm going to merge this now.
Thanks!

Nevertheless, there are still some structural changes I'd like to make as well as rename some methods and variables, but rather than annoy you with those details I will just do this additional refactoring myself after the merge; hope you don't mind.
You have also inspired me to implement an ObjExporter class, similar to your ExportBam class, so export to .obj should then also be coded in a more readable way.

**Pull request merged**
